apiVersion: cache.example.com/v1alpha1
kind: Memcached
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cache.example.com/v1alpha1","kind":"Memcached","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"memcached-operator"},"name":"memcached-sample","namespace":"kube-system"},"spec":null}
  creationTimestamp: "2025-06-26T08:42:56Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: memcached-operator
  name: memcached-sample
  namespace: kube-system
  resourceVersion: "3992198"
  uid: dd74b7f0-d8b6-4f4b-a52b-bfb6168809ac
